apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImdoY3IuaW8iOiB7DQogICAgICAiYXV0aCI6ICJaMjl5WW5WdWIzWXRZV3hsZUdGdVpHVnlPbWRvY0Y4MFl6RnlORkpOY2xGMFF6UTVaSEkxV20xeVptUmxjRlJyWkRoUmVFRXpSM2xhTTNZPSINCiAgICB9DQogIH0NCn0=
type: kubernetes.io/dockerconfigjson
